WORD_QUERY_LIST = ["nigger","kike","jew","white","jesus",
                   "hitler","christian","muslim","troon",
                   "tranny","genocide","kill","goy",
                   "globalist","fren","comfy","globohomo",
                   "pogrom","society","collapse",
                   "blood","kosher","vermin","military","pajeet",
                   "shitskin"] # e.g., n-word, k-word, etc.

BLUR_WORDS = {
    "nigger":"n-word",
    "jew":"jew",
    "hitler":"hitler",
    "kike":"k-word",
    "poo":"poo (anti-Indian slur)",
    "white":"white",
    "jesus":"jesus",
    "christian":"christian",
    "muslim":"muslim",
    "troon":"troon",
    "tranny":"tranny",
    "genocide":"genocide",
    "kill":"kill",
    "goy":"goy",
    "globohomo":"globohomo", # aka, colonial imperialism as it defined by russian-style fascists; or perhaps some NWO-style plan by the globalists (jews) as defined by some far right/MAGA conservatives
    "globalist":"globalist",
    "fren":"fren",
    "comfy":"comfy",
    "pogrom":"pogrom",
    "society":"society",
    "collapse":"collapse",
    "kosher":"kosher",
    "blood":"blood",
    "vermin":"vermin",
    "shitskin":"shitskin",
    "pajeet":"pajeet",
    "military":"military"
}